message(WARNING "Entering CMakeCythonInformation.cmake")

#set(CMAKE_Cython_CREATE_SHARED_LIBRARY)
#set(CMAKE_Cython_CREATE_SHARED_MODULE)
#set(CMAKE_Cython_CREATE_STATIC_LIBRARY)
#set(CMAKE_Cython_COMPILE_OBJECT)
#set(CMAKE_Cython_LINK_EXECUTABLE)

if(NOT CMAKE_Cython_COMPILE_OPTIONS_PIC)
    set(CMAKE_Cython_COMPILE_OPTIONS_PIC ${CMAKE_C_COMPILE_OPTIONS_PIC})
endif()

if(NOT CMAKE_Cython_COMPILE_OPTIONS_PIE)
    set(CMAKE_Cython_COMPILE_OPTIONS_PIE ${CMAKE_C_COMPILE_OPTIONS_PIE})
endif()
if(NOT CMAKE_Cython_LINK_OPTIONS_PIE)
    set(CMAKE_Cython_LINK_OPTIONS_PIE ${CMAKE_C_LINK_OPTIONS_PIE})
endif()
if(NOT CMAKE_Cython_LINK_OPTIONS_NO_PIE)
    set(CMAKE_Cython_LINK_OPTIONS_NO_PIE ${CMAKE_C_LINK_OPTIONS_NO_PIE})
endif()

if(NOT CMAKE_Cython_COMPILE_OPTIONS_DLL)
    set(CMAKE_Cython_COMPILE_OPTIONS_DLL ${CMAKE_C_COMPILE_OPTIONS_DLL})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_CREATE_Cython_FLAGS)
    set(CMAKE_SHARED_LIBRARY_CREATE_Cython_FLAGS ${CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_Cython_FLAGS)
    set(CMAKE_SHARED_LIBRARY_Cython_FLAGS ${CMAKE_SHARED_LIBRARY_C_FLAGS})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_Cython_FLAGS)
    set(CMAKE_SHARED_LIBRARY_LINK_Cython_FLAGS ${CMAKE_SHARED_LIBRARY_LINK_C_FLAGS})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG)
    set(CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG ${CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG_SEP)
    set(CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG_SEP ${CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_RPATH_LINK_Cython_FLAG)
    set(CMAKE_SHARED_LIBRARY_RPATH_LINK_Cython_FLAG ${CMAKE_SHARED_LIBRARY_RPATH_LINK_C_FLAG})
endif()

if(NOT DEFINED CMAKE_EXE_EXPORTS_Cython_FLAG)
    set(CMAKE_EXE_EXPORTS_Cython_FLAG ${CMAKE_EXE_EXPORTS_C_FLAG})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_SONAME_Cython_FLAG)
    set(CMAKE_SHARED_LIBRARY_SONAME_Cython_FLAG ${CMAKE_SHARED_LIBRARY_SONAME_C_FLAG})
endif()


if(NOT DEFINED CMAKE_SHARED_MODULE_CREATE_Cython_FLAGS)
    set(CMAKE_SHARED_MODULE_CREATE_Cython_FLAGS ${CMAKE_SHARED_MODULE_CREATE_C_FLAGS})
endif()

if(NOT DEFINED CMAKE_SHARED_MODULE_Cython_FLAGS)
    set(CMAKE_SHARED_MODULE_Cython_FLAGS ${CMAKE_SHARED_MODULE_C_FLAGS})
endif()

if(NOT DEFINED CMAKE_EXECUTABLE_RUNTIME_Cython_FLAG)
    set(CMAKE_EXECUTABLE_RUNTIME_Cython_FLAG ${CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG})
endif()

if(NOT DEFINED CMAKE_EXECUTABLE_RUNTIME_Cython_FLAG_SEP)
    set(CMAKE_EXECUTABLE_RUNTIME_Cython_FLAG_SEP ${CMAKE_SHARED_LIBRARY_RUNTIME_Cython_FLAG_SEP})
endif()

if(NOT DEFINED CMAKE_EXECUTABLE_RPATH_LINK_Cython_FLAG)
    set(CMAKE_EXECUTABLE_RPATH_LINK_Cython_FLAG ${CMAKE_SHARED_LIBRARY_RPATH_LINK_Cython_FLAG})
endif()

if(NOT DEFINED CMAKE_SHARED_LIBRARY_LINK_Cython_WITH_RUNTIME_PATH)
    set(CMAKE_SHARED_LIBRARY_LINK_Cython_WITH_RUNTIME_PATH ${CMAKE_SHARED_LIBRARY_LINK_C_WITH_RUNTIME_PATH})
endif()

if(NOT CMAKE_INCLUDE_FLAG_Cython)
    set(CMAKE_INCLUDE_FLAG_Cython ${CMAKE_INCLUDE_FLAG_C})
endif()

if(NOT CMAKE_Cython_COMPILE_OBJECT)
    ## Typical definition
#    set(CMAKE_Cython_COMPILE_OBJECT
#            "<CMAKE_Cython_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -c <SOURCE> -o <OBJECT>")
    ## Approach 1
#    set(CMAKE_Cython_COMPILE_OBJECT
#            "<CMAKE_Cython_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")
    ## Approach 2
    string(REPLACE "<SOURCE>" "<OBJECT>.c" CMAKE_C_COMPILE_OBJECT_replaced "${CMAKE_C_COMPILE_OBJECT}")
    set(CMAKE_Cython_COMPILE_OBJECT
            "<CMAKE_Cython_COMPILER> -o <OBJECT>.c <SOURCE>"
            "${CMAKE_C_COMPILE_OBJECT_replaced}"
    )
endif()

set(CMAKE_Cython_CREATE_SHARED_LIBRARY ${CMAKE_C_CREATE_SHARED_LIBRARY})
set(CMAKE_Cython_CREATE_SHARED_MODULE ${CMAKE_C_CREATE_SHARED_MODULE})
set(CMAKE_Cython_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})

set(CMAKE_Cython_INFORMATION_LOADED 1)
