files_to_sync:
  - src: .distro/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "protect changelog"
      - "- plans/rpmlint.fmf"
  - .packit.yaml

upstream_package_name: cython-cmake
specfile_path: .distro/cython-cmake.spec
downstream_package_name: cython-cmake
upstream_tag_template: v{version}

targets: &targets
  - fedora-all-x86_64
  - fedora-all-aarch64
  # TODO: Package for epel-10 once scikit-build-core is packaged there
#  - epel-10-x86_64
#  - epel-10-aarch64

jobs:
  - &copr_build
    job: copr_build
    trigger: pull_request
  - &tests
    job: tests
    trigger: pull_request
    fmf_path: .distro
  - <<: *copr_build
    trigger: release
    owner: "@scikit-build"
    project: release
  - <<: *tests
    trigger: release
  - <<: *copr_build
    trigger: commit
    branch: main
    owner: "@scikit-build"
    project: nightly
  - <<: *tests
    trigger: commit
    branch: main
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
